"""Pipeline orchestrator.   OWNER: M6 (Integration).

This is the ONLY file that calls into every member's module.  It exists so that
no member ever has to import another member's code, which means:

  * you cannot break someone else's module by changing yours
  * a module that is still a stub, or that raises, degrades ONE block of the
    response to null/stub and adds a warning.  It never 500s the request.
  * `module_status` tells the frontend which panels to grey out, so the UI is
    honest about what is finished at any moment during the build.

Members: do not edit this file.  If the orchestrator is calling your function
with the wrong arguments, tell M6 - do not "fix" it locally, because your fix
will conflict with everyone else's.
"""
from __future__ import annotations

import hashlib
import time
import uuid
from datetime import datetime, timezone

from .core.config import SCHEMA_VERSION
from .intel import confidence as m3_confidence
from .intel import risk_score as m3_risk
from .parsing import auth_checks as m2_auth
from .parsing import header_parser as m1_headers
from .parsing import ip_ranking as m2_rank
from .parsing import received_chain as m1_chain
from .report import custody_log as m4_custody
from .report import report_builder as m4_report


def _utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _ms(start: float) -> int:
    return int((time.perf_counter() - start) * 1000)


def _state(module) -> str:
    """live | stub - read the module's IS_STUB flag."""
    return "stub" if getattr(module, "IS_STUB", True) else "live"


def _empty_headers() -> dict:
    """Contract-shaped empty headers block, used when M1's module errors."""
    return {
        "from": {"display_name": None, "address": None, "domain": None},
        "reply_to": None, "return_path": None, "to": [], "cc": [],
        "subject": None, "message_id": None, "message_id_domain": None,
        "date": None, "date_raw": None, "x_mailer": None,
        "raw_header_count": 0, "missing_headers": [], "body_preview": "",
        "anomalies": [],
    }


def run_analysis(raw_email: str, *, source: str = "paste",
                 filename: str | None = None,
                 skip_geoip: bool = False,
                 include_body_heuristics: bool = True) -> dict:
    """Run the full pipeline and return a contract-shaped dict.

    Every stage is individually guarded.  Read the pattern once and you can see
    exactly why a half-finished team still gets a working demo.
    """
    t_total = time.perf_counter()
    warnings: list[str] = []
    raw_bytes = raw_email.encode("utf-8", errors="replace")

    result: dict = {
        "schema_version": SCHEMA_VERSION,
        "analysis_id": str(uuid.uuid4()),
        "analyzed_at": _utc_now(),
        "input": {
            "source": source,
            "filename": filename,
            "byte_size": len(raw_bytes),
            "sha256": hashlib.sha256(raw_bytes).hexdigest(),
        },
        "headers": {}, "received_chain": [], "chain_integrity": {},
        "authentication": {}, "ip_candidates": [],
        "origin": {}, "map_hops": [], "risk": {}, "report": None,
        "warnings": warnings,
        "timings_ms": {"parse": 0, "auth": 0, "geoip": 0, "score": 0, "report": 0, "total": 0},
        "module_status": {
            "parsing": _state(m1_headers), "auth": _state(m2_auth),
            "ranking": _state(m2_rank), "geoip": _state(m3_confidence),
            "scoring": _state(m3_risk), "report": _state(m4_report),
        },
    }

    # ---- M1: headers + received chain -------------------------------------
    t = time.perf_counter()
    try:
        result["headers"] = m1_headers.parse_headers(raw_email)
    except Exception as exc:
        warnings.append(f"Header parsing failed: {exc}")
        result["module_status"]["parsing"] = "error"
        result["headers"] = _empty_headers()
    try:
        result["received_chain"] = m1_chain.parse_received_chain(raw_email)
    except Exception as exc:
        warnings.append(f"Received-chain parsing failed: {exc}")
        result["module_status"]["parsing"] = "error"
    try:
        result["chain_integrity"] = m1_chain.assess_chain_integrity(result["received_chain"])
    except Exception as exc:
        warnings.append(f"Chain integrity assessment failed: {exc}")
        result["chain_integrity"] = {
            "hop_count": len(result["received_chain"]), "timestamps_monotonic": True,
            "backward_time_jumps": 0, "largest_gap_seconds": 0,
            "gaps_suspected": False, "malformed_hops": 0, "notes": [],
        }
    result["timings_ms"]["parse"] = _ms(t)

    # ---- M2: authentication + IP trust ranking ----------------------------
    t = time.perf_counter()
    try:
        result["authentication"] = m2_auth.evaluate_authentication(raw_email, result["headers"])
    except Exception as exc:
        warnings.append(f"Authentication evaluation failed: {exc}")
        result["module_status"]["auth"] = "error"
        empty = {"result": "none", "domain": None, "selector": None,
                 "policy": None, "raw": None, "source": None}
        result["authentication"] = {
            "spf": dict(empty), "dkim": dict(empty), "dmarc": dict(empty), "arc": dict(empty),
            "alignment": {"spf_aligned": False, "dkim_aligned": False,
                          "from_vs_returnpath_match": False, "envelope_from_domain": None},
            "verified_by": None, "self_asserted_only": False,
        }
    try:
        result["ip_candidates"] = m2_rank.rank_ip_candidates(
            result["received_chain"], result["authentication"])
    except Exception as exc:
        warnings.append(f"IP ranking failed: {exc}")
        result["module_status"]["ranking"] = "error"
    result["timings_ms"]["auth"] = _ms(t)

    # ---- M3: origin + confidence + map ------------------------------------
    t = time.perf_counter()
    try:
        origin, map_hops = m3_confidence.build_origin(
            result["ip_candidates"], result["authentication"],
            result["chain_integrity"], skip_geoip=skip_geoip)
        result["origin"], result["map_hops"] = origin, map_hops
    except Exception as exc:
        warnings.append(f"Origin/geolocation failed: {exc}")
        result["module_status"]["geoip"] = "error"
        result["origin"] = {
            "selected_ip": None, "selected_from_hop": None,
            "geo": {"country": None, "country_code": None, "region": None,
                    "city": None, "lat": None, "lon": None, "isp": None,
                    "org": None, "asn": None, "is_datacenter": False,
                    "is_proxy": False, "is_mobile": False,
                    "lookup_source": "unavailable"},
            "infrastructure_type": "unknown", "confidence": "low",
            "confidence_reasons": ["Origin analysis unavailable for this message."],
            "statement": m3_confidence.NO_ORIGIN_STATEMENT,
        }
    result["timings_ms"]["geoip"] = _ms(t)

    # ---- M3: risk score ----------------------------------------------------
    t = time.perf_counter()
    body = result["headers"].get("body_preview", "") if include_body_heuristics else ""
    try:
        result["risk"] = m3_risk.score_risk(
            result["headers"], result["authentication"], result["origin"],
            result["chain_integrity"], body)
    except Exception as exc:
        warnings.append(f"Risk scoring failed: {exc}")
        result["module_status"]["scoring"] = "error"
        result["risk"] = {
            "score": 0, "band": "low", "verdict": "inconclusive",
            "signals": [{"code": c, "label": l, "points": p,
                         "triggered": False, "evidence": None}
                        for c, l, p in m3_risk.SIGNAL_DEFS],
        }
    result["timings_ms"]["score"] = _ms(t)

    # ---- M4: report + custody log -----------------------------------------
    t = time.perf_counter()
    try:
        evidence_hash = m4_report.canonical_evidence_hash(result)
        entry_no, prev_hash = m4_custody.append_custody_entry(
            result["analysis_id"], evidence_hash,
            {"filename": filename, "byte_size": result["input"]["byte_size"]})
        aid = result["analysis_id"]
        result["report"] = {
            "report_id": f"RPT-{datetime.now(timezone.utc):%Y%m%d}-{entry_no:04d}",
            "generated_at": _utc_now(),
            "json_url": f"/api/v1/report/{aid}.json",
            "pdf_url": f"/api/v1/report/{aid}.pdf",
            "evidence_sha256": evidence_hash,
            "custody_log_entry": entry_no or None,
            "previous_entry_hash": prev_hash,
        }
        if not entry_no:
            warnings.append("Custody log entry could not be written; report is unlogged.")
    except Exception as exc:
        warnings.append(f"Report generation failed: {exc}")
        result["module_status"]["report"] = "error"
        result["report"] = None
    result["timings_ms"]["report"] = _ms(t)

    result["timings_ms"]["total"] = _ms(t_total)
    return result
