"""Pydantic models = the API contract, executable.   OWNER: M6 (Integration).

FROZEN after Day-1 morning.  If you are not M6, do not edit this file.
Need a change?  Follow API_CONTRACT.md section 8.

Why this exists: these models validate the pipeline's output on every request.
If your module returns a wrong-shaped dict, you get a loud error here instead of
a silently broken dashboard at 2am.
"""
from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

Confidence = Literal["high", "medium", "low"]
TrustTier = Literal["provider_observed", "transit_relay", "client_asserted", "unverifiable"]
InfraType = Literal[
    "residential_isp", "corporate", "hosting", "vpn", "tor",
    "webmail_provider", "mobile_carrier", "unknown",
]
AuthResult = Literal["pass", "fail", "softfail", "neutral", "none", "temperror", "permerror"]
RiskBand = Literal["low", "medium", "high", "critical"]
Verdict = Literal["likely_legitimate", "inconclusive", "suspicious", "likely_phishing"]
LookupSource = Literal["ip-api.com", "geolite2", "cache", "mock", "unavailable"]
ModuleState = Literal["live", "stub", "error"]
Severity = Literal["info", "low", "medium", "high"]


class Mailbox(BaseModel):
    display_name: str | None = None
    address: str | None = None
    domain: str | None = None


class Anomaly(BaseModel):
    code: str
    severity: Severity = "info"
    detail: str | None = None


class InputMeta(BaseModel):
    source: Literal["paste", "file"]
    filename: str | None = None
    byte_size: int = 0
    sha256: str = ""


class Headers(BaseModel):
    """Produced by M1 - parsing/header_parser.py::parse_headers()"""
    from_: Mailbox = Field(default_factory=Mailbox, alias="from")
    reply_to: Mailbox | None = None
    return_path: Mailbox | None = None
    to: list[Mailbox] = Field(default_factory=list)
    cc: list[Mailbox] = Field(default_factory=list)
    subject: str | None = None
    message_id: str | None = None
    message_id_domain: str | None = None
    date: str | None = None
    date_raw: str | None = None
    x_mailer: str | None = None
    raw_header_count: int = 0
    missing_headers: list[str] = Field(default_factory=list)
    body_preview: str = ""
    anomalies: list[Anomaly] = Field(default_factory=list)

    model_config = {"populate_by_name": True}


class ReceivedHop(BaseModel):
    """Produced by M1 - parsing/received_chain.py::parse_received_chain()

    hop_index == 1 means CLOSEST TO SENDER (the bottom-most Received header).
    """
    hop_index: int
    raw: str = ""
    from_host: str | None = None
    from_ip: str | None = None
    by_host: str | None = None
    by_ip: str | None = None
    protocol: str | None = None
    tls: bool = False
    timestamp: str | None = None
    timestamp_raw: str | None = None
    is_private_ip: bool = False
    parse_ok: bool = True


class ChainIntegrity(BaseModel):
    """Produced by M1 - parsing/received_chain.py::assess_chain_integrity()"""
    hop_count: int = 0
    timestamps_monotonic: bool = True
    backward_time_jumps: int = 0
    largest_gap_seconds: int = 0
    gaps_suspected: bool = False
    malformed_hops: int = 0
    notes: list[str] = Field(default_factory=list)


class AuthMechanism(BaseModel):
    result: AuthResult = "none"
    domain: str | None = None
    selector: str | None = None
    policy: str | None = None
    raw: str | None = None
    source: str | None = None


class Alignment(BaseModel):
    spf_aligned: bool = False
    dkim_aligned: bool = False
    from_vs_returnpath_match: bool = False
    envelope_from_domain: str | None = None


class Authentication(BaseModel):
    """Produced by M2 - parsing/auth_checks.py::evaluate_authentication()"""
    spf: AuthMechanism = Field(default_factory=AuthMechanism)
    dkim: AuthMechanism = Field(default_factory=AuthMechanism)
    dmarc: AuthMechanism = Field(default_factory=AuthMechanism)
    arc: AuthMechanism = Field(default_factory=AuthMechanism)
    alignment: Alignment = Field(default_factory=Alignment)
    verified_by: str | None = None
    self_asserted_only: bool = False


class IpCandidate(BaseModel):
    """Produced by M2 - parsing/ip_ranking.py::rank_ip_candidates()
    List is SORTED: index 0 is the most credible candidate.
    """
    ip: str
    hop_index: int
    trust_tier: TrustTier = "unverifiable"
    trust_score: float = 0.0
    observed_by: str | None = None
    observed_by_is_trusted_receiver: bool = False
    reasons: list[str] = Field(default_factory=list)
    excluded: bool = False
    exclusion_reason: str | None = None


class Geo(BaseModel):
    country: str | None = None
    country_code: str | None = None
    region: str | None = None
    city: str | None = None
    lat: float | None = None
    lon: float | None = None
    isp: str | None = None
    org: str | None = None
    asn: str | None = None
    is_datacenter: bool = False
    is_proxy: bool = False
    is_mobile: bool = False
    lookup_source: LookupSource = "unavailable"


class Origin(BaseModel):
    """Produced by M3 - intel/confidence.py::build_origin()

    `confidence` is NEVER null.  If it cannot be computed it is "low".
    `statement` is NEVER empty - see API_CONTRACT.md section 6 for the wording.
    """
    selected_ip: str | None = None
    selected_from_hop: int | None = None
    geo: Geo = Field(default_factory=Geo)
    infrastructure_type: InfraType = "unknown"
    confidence: Confidence = "low"
    confidence_reasons: list[str] = Field(default_factory=list)
    statement: str = ""


class MapHop(BaseModel):
    """Produced by M3.  Leaflet-ready; only hops that geolocated successfully."""
    hop_index: int
    ip: str
    lat: float
    lon: float
    label: str = ""
    confidence: Confidence = "low"
    is_selected_origin: bool = False


class RiskSignal(BaseModel):
    code: str
    label: str
    points: int
    triggered: bool = False
    evidence: str | None = None


class Risk(BaseModel):
    """Produced by M3 - intel/risk_score.py::score_risk()
    `signals` always contains all 5 rules, triggered True or False.
    """
    score: int = 0
    band: RiskBand = "low"
    verdict: Verdict = "inconclusive"
    signals: list[RiskSignal] = Field(default_factory=list)


class ReportMeta(BaseModel):
    """Produced by M4 - report/report_builder.py.  null while stubbed."""
    report_id: str
    generated_at: str
    json_url: str | None = None
    pdf_url: str | None = None
    evidence_sha256: str
    custody_log_entry: int | None = None
    previous_entry_hash: str | None = None


class Timings(BaseModel):
    parse: int = 0
    auth: int = 0
    geoip: int = 0
    score: int = 0
    report: int = 0
    total: int = 0


class ModuleStatus(BaseModel):
    parsing: ModuleState = "stub"
    auth: ModuleState = "stub"
    ranking: ModuleState = "stub"
    geoip: ModuleState = "stub"
    scoring: ModuleState = "stub"
    report: ModuleState = "stub"


class AnalysisResponse(BaseModel):
    """THE response.  Every key is always present; absent data is null / []."""
    schema_version: str = "1.0"
    analysis_id: str
    analyzed_at: str
    input: InputMeta
    headers: Headers = Field(default_factory=Headers)
    received_chain: list[ReceivedHop] = Field(default_factory=list)
    chain_integrity: ChainIntegrity = Field(default_factory=ChainIntegrity)
    authentication: Authentication = Field(default_factory=Authentication)
    ip_candidates: list[IpCandidate] = Field(default_factory=list)
    origin: Origin = Field(default_factory=Origin)
    map_hops: list[MapHop] = Field(default_factory=list)
    risk: Risk = Field(default_factory=Risk)
    report: ReportMeta | None = None
    warnings: list[str] = Field(default_factory=list)
    timings_ms: Timings = Field(default_factory=Timings)
    module_status: ModuleStatus = Field(default_factory=ModuleStatus)


class AnalyzeOptions(BaseModel):
    skip_geoip: bool = False
    include_body_heuristics: bool = True


class AnalyzeRequest(BaseModel):
    raw_email: str = ""
    options: AnalyzeOptions = Field(default_factory=AnalyzeOptions)


class ErrorBody(BaseModel):
    code: str
    message: str
    detail: Any | None = None


class ErrorResponse(BaseModel):
    schema_version: str = "1.0"
    error: ErrorBody
